train_dataset: zheng
val_dataset: zheng
shuffle_size: 1024
label: quality
seed: 42
load_model: None
epochs: 200
batch_size: 512
latent_dimension: 8
learning_rate: 0.001
coefficients:
  alpha: 0.00001
  beta: 0.001
  gamma: 0.0005
coefficients_raise: 20
period_reconstruction_plot: 20
index_tracked_sample: 5
eval_data:
  - zheng
  - synth
  - ptb
