train_dataset:
  name: 'synth'
  split: 'train'
  shuffle_size: 1024
  batch_size: 1024
val_dataset:
  name: 'medalcare'
  split: 'validation'
  shuffle_size: 1024
  batch_size: 1024
save_results_path: ../results/
seed: 42
load_model: None
epochs: 1000
latent_dimension: 16
learning_rate: 0.002
coefficients:
  alpha: 0.001
  beta: 0.004
  gamma: 0.1
coefficients_raise: 50
period_reconstruction_plot: 50
index_tracked_sample: 5
eval_data_disentanglement:
  synth:
    name: 'synth'
    splits: [ 'train' ]
eval_data_anomaly:
  zheng:
    name: 'zheng'
    splits: [ 'train' ]
eval_data_personalization:
  icentia11k:
    name: 'icentia11k'
    splits: [ '1', '2', '3', '4', '5', '6', '7', '8', '9' ]
    epochs: 50
