train_dataset:
  name: 'ptb'
  split: 'train'
  shuffle_size: 1024
  batch_size: 1024
val_dataset:
  name: 'zheng'
  split: 'train'
  shuffle_size: 1024
  batch_size: 1024
save_results_path: ../results/
seed: 42
load_model: None
epochs: 1000
latent_dimension: 12
learning_rate: 0.0001
coefficients:
  alpha: 1.0
  beta: 4.0
  gamma: 1.0
coefficients_raise: 20
early_stopping: 50000
period_reconstruction_plot: 20
index_tracked_sample: 5
eval_data:
  synth:
    name: 'synth'
    splits: [ 'train' ]
    fine_tune: False
  zheng:
    name: 'zheng'
    splits: [ 'train' ]
    fine_tune: False
  medalcare:
    name: 'medalcare'
    splits: [ 'train' ]
    fine_tune: False
  ptb:
    name: 'ptb'
    splits: [ 'train' ]
    fine_tune: False
  icentia11k:
    name: 'icentia11k'
    splits: [ '1', '2', '3', '4', '5', '6', '7', '8', '9' ]
    fine_tune: True
    epochs: 50
    batch_size: 1024
